;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-lambda-reader.ss" "lang")((modname 479-threatening) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(define QUEENS 8)
; A QP is a structure:
;   (make-posn CI CI)
; A CI is an N in [0,QUEENS).
; interpretation (make-posn c r) denotes the square at
; the r-th row and c-th column

; QP QP -> Boolean
; return #true if the queens on the squares qp1 and qp2 threaten each other

;  01234567
; 0.o....o.
; 1.o...o..
; 2.Y..o...
; 3.o.o....
; 4ooo.....
; 5oXoooooo
; 6ooo.....
; 7.o.o....
(check-expect (threatening? (make-posn 1 5) (make-posn 1 2)) #true)

;  01234567
; 0.o....o.
; 1.o...Y..
; 2.o..o...
; 3.o.o....
; 4ooo.....
; 5oXoooooo
; 6ooo.....
; 7.o.o....
(check-expect (threatening? (make-posn 1 5) (make-posn 5 1)) #true)

;  01234567
; 0.o....o.
; 1.o...o..
; 2.o..o...
; 3.o.o....
; 4ooo.....
; 5oXoooooY
; 6ooo.....
; 7.o.o....
(check-expect (threatening? (make-posn 1 5) (make-posn 7 5)) #true)

;  01234567
; 0.o....o.
; 1.o...o..
; 2.o..o...
; 3.o.o....
; 4ooo.....
; 5oXoooooo
; 6ooY.....
; 7.o.o....
(check-expect (threatening? (make-posn 1 5) (make-posn 2 6)) #true)

;  01234567
; 0.o....o.
; 1.o...o..
; 2.o..o...
; 3.o.o....
; 4ooo.....
; 5oXoooooo
; 6ooo.....
; 7.Y.o....
(check-expect (threatening? (make-posn 1 5) (make-posn 1 7)) #true)

;  01234567
; 0.o....o.
; 1.o...o..
; 2.o..o...
; 3.o.o....
; 4ooo.....
; 5oXoooooo
; 6Yoo.....
; 7.o.o....
(check-expect (threatening? (make-posn 1 5) (make-posn 0 6)) #true)

;  01234567
; 0.o....o.
; 1.o...o..
; 2.o..o...
; 3.o.o....
; 4ooo.....
; 5YXoooooo
; 6ooo.....
; 7.o.o....
(check-expect (threatening? (make-posn 1 5) (make-posn 0 5)) #true)

;  01234567
; 0.o....o.
; 1.o...o..
; 2.o..o...
; 3.o.o....
; 4Yoo.....
; 5oXoooooo
; 6ooo.....
; 7.o.o....
(check-expect (threatening? (make-posn 1 5) (make-posn 0 4)) #true)

;  01234567
; 0.oY...o.
; 1.o...o..
; 2.o..o...
; 3.o.o....
; 4ooo.....
; 5oXoooooo
; 6ooo.....
; 7.o.o....
(check-expect (threatening? (make-posn 1 5) (make-posn 2 0)) #false)

;  01234567
; 0.o....o.
; 1.o...o..
; 2.o..o.Y.
; 3.o.o....
; 4ooo.....
; 5oXoooooo
; 6ooo.....
; 7.o.o....
(check-expect (threatening? (make-posn 1 5) (make-posn 6 2)) #false)

;  01234567
; 0.o....o.
; 1.o...o..
; 2.o..o...
; 3.o.o....
; 4ooo.....
; 5oXoooooo
; 6ooo.....
; 7.oYo....
(check-expect (threatening? (make-posn 1 5) (make-posn 2 7)) #false)

(define (threatening? qp1 qp2)
  (local ((define hor (= (posn-y qp1) (posn-y qp2)))
          (define ver (= (posn-x qp1) (posn-x qp2)))
          (define diag1 (= (+ (posn-x qp1) (posn-y qp1))
                           (+ (posn-x qp2) (posn-y qp2))))
          (define diag2 (= (- (posn-x qp1) (posn-y qp1))
                           (- (posn-x qp2) (posn-y qp2)))))
    (or hor ver diag1 diag2)))
